# Generated by Django 5.2.1 on 2026-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
