# Generated by Django 5.2.1 on 2025-06-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_followersmodel_followingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingmodel',
            name='user_obj',
        ),
        migrations.DeleteModel(
            name='FollowersModel',
        ),
        migrations.DeleteModel(
            name='FollowingModel',
        ),
    ]
