# Generated by Django 5.2.1 on 2026-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
