# Generated by Django 5.2.1 on 2026-07-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notificationmodel_accept_notificationmodel_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='reject',
        ),
    ]
