# Generated by Django 5.2.1 on 2025-06-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_followersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersModel',
        ),
    ]
