# Generated by Django 5.2.1 on 2025-06-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_followersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersModel',
        ),
    ]
