# Generated by Django 5.2.1 on 2025-06-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_followermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerModel',
        ),
    ]
