# Generated by Django 5.2.1 on 2025-06-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_delete_followermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowingModel',
        ),
    ]
