# Generated by Django 5.2.1 on 2026-08-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewitems',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.reviewmodel'),
        ),
        migrations.AddField(
            model_name='watchlistmodel',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlistitems',
            name='watchlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.watchlistmodel'),
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlistitems',
            name='wishlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.wishlistmodel'),
        ),
    ]
